In [34]:
import json
import pandas as pd
import numpy as np

#Add path of files
dfEvi = pd.read_excel('C:\\Users\\utkarsh.dixit\\Downloads\\Datasets\\evi\\2021-retrospective-review-official.xlsx', sheet_name = ['Criteria','GNI','HAI','EVI'])
isoCountry = open('C:\\Users\\utkarsh.dixit\\PycharmProjects\\PovertyVulnerabilityAnalysis\\isonewcountryjs.json',)
countryDictionary = json.load(isoCountry)

In [10]:
#Sheet1: Criteria
indicatorCode = ['GNI','HAI', 'EVI']
uniqueYears = dfEvi['Criteria']['Year'].unique()
dfEvi['Criteria'] = dfEvi['Criteria'].drop(columns = ['CCode','Status','Country'])
for ele in uniqueYears:
    dfEvi['Criteria'][ele] = np.nan
dfEvi['Criteria'].insert(2, 'IndicatorCode', '')
isoGrouped = dfEvi['Criteria'].groupby('Iso', sort = False)

Final_df = pd.DataFrame()
z = 0
for groupKey in isoGrouped.groups.keys():
    temp = isoGrouped.get_group(groupKey).apply(lambda x:x)
    temp = temp.reset_index(drop=True)
    for (code,i) in enumerate(indicatorCode,0):
        values = isoGrouped.get_group(groupKey)[i].tolist()
        temp.loc[code,uniqueYears] = values
        temp.loc[code,['IndicatorCode']] = i
    temp = temp.drop(columns = ['Year','GNI','HAI','EVI'])
    temp = temp.drop(range(3,temp.shape[0]))
    z = z + 1
    if z == 1:
        Final_df = temp
    else:
        Final_df = Final_df.append(temp, ignore_index=True)
        
Final_df.head(5)

,Iso,IndicatorCode,2002,2003,2004,2005,2006,2007,2008,2009,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,AFG,GNI,126.155704,123.001001,150.660109,183.633741,214.908406,226.579818,241.776983,281.245321,...,398.687006,451.463254,518.238832,579.915309,613.219640,599.455916,564.747746,534.544629,518.717466,512.512990
1,AFG,HAI,5.788194,6.033005,6.565748,7.098717,8.822967,10.190499,13.038878,14.345812,...,25.595041,28.932975,31.184121,32.855428,34.250375,36.325848,38.142928,39.986104,41.396926,41.993067
2,AFG,EVI,50.110583,50.902468,50.819678,50.122079,48.788140,47.643518,47.001208,46.105175,...,43.498666,42.890286,42.742670,42.722336,42.611061,42.831559,43.163960,43.339308,44.440394,44.838924
3,DZA,GNI,1556.730578,1600.420575,1670.269484,1783.826029,1980.592536,2311.674191,2703.833006,3153.085100,...,4326.287808,4457.381928,4764.627591,5110.944361,5412.186689,5299.524194,4918.685640,4401.028726,4108.114884,3997.062551
4,DZA,HAI,74.539631,75.957694,77.308895,78.301119,79.685210,80.661367,81.497302,80.480662,...,87.157678,88.052419,88.357145,88.694174,88.956363,89.237486,89.507670,89.820033,90.055917,90.189419

In [11]:
#Sheet2: GNI
indicatorCodeSecond = ['GNI']
uniqueYearsSecond = dfEvi['GNI']['Year'].unique()
dfEvi['GNI'] = dfEvi['GNI'].drop(columns = ['CCode','Status','Country'])

for ele in uniqueYearsSecond:
    dfEvi['GNI'][ele] = np.nan
dfEvi['GNI'].insert(2, 'IndicatorCode', '')
isoGrouped = dfEvi['GNI'].groupby('Iso', sort = False)

Final_dfSecond = pd.DataFrame()
z = 0
for groupKey in isoGrouped.groups.keys():
    temp = isoGrouped.get_group(groupKey).apply(lambda x:x)
    temp = temp.reset_index(drop=True)
    for (code,i) in enumerate(indicatorCodeSecond,0):
        values = isoGrouped.get_group(groupKey)[i].tolist()
        temp.loc[code,uniqueYearsSecond] = values
        temp.loc[code,['IndicatorCode']] = i
    temp = temp.drop(columns = ['Year','GNI'])
    temp = temp.drop(range(1,temp.shape[0]))
    z = z + 1
    if z == 1:
        Final_dfSecond = temp
    else:
        Final_dfSecond = Final_dfSecond.append(temp, ignore_index=True)
        
Final_dfSecond.head(5)

,Iso,IndicatorCode,2002,2003,2004,2005,2006,2007,2008,2009,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,AFG,GNI,126.155704,123.001001,150.660109,183.633741,214.908406,226.579818,241.776983,281.245321,...,398.687006,451.463254,518.238832,579.915309,613.219640,599.455916,564.747746,534.544629,518.717466,512.512990
1,DZA,GNI,1556.730578,1600.420575,1670.269484,1783.826029,1980.592536,2311.674191,2703.833006,3153.085100,...,4326.287808,4457.381928,4764.627591,5110.944361,5412.186689,5299.524194,4918.685640,4401.028726,4108.114884,3997.062551
2,AGO,GNI,481.645160,481.851118,573.749769,681.293205,845.530891,1065.444979,1404.304098,1871.269158,...,3113.230325,3255.536740,3607.133850,4120.685181,4649.465907,4797.577151,4460.553470,3942.502200,3469.590511,3207.259882
3,ATG,GNI,9642.049232,9817.871532,9835.052268,9974.130782,10512.529009,11418.634445,12498.911945,13690.801684,...,13731.057549,12814.173678,12606.234163,12678.638689,12991.239144,13248.332153,13726.431046,14249.540966,15181.114052,16072.130129
4,ARG,GNI,8307.725744,7937.894561,6673.934030,5305.398255,4075.113190,4222.660008,4746.789488,5647.988675,...,8303.847790,9315.454571,10740.272989,12159.554151,13042.958661,13588.443172,13348.584390,13385.025737,12938.563492,12403.637013

In [20]:
dfEvi['HAI'].head(20)

,Iso,Year,IndicatorCode,HAI,U5M-Value,U5M-Index,MMR-Value,MMR-Index,STU-Value,STU-Index,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,AFG,2002,,5.788194,128.691267,28.065899,1450.0,0.000000,54.6,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AFG,2003,,6.033005,124.584845,30.554640,1390.0,0.000000,54.4,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,2004,,6.565748,120.430040,33.072703,1300.0,0.000000,54.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AFG,2005,,7.098717,116.272989,35.592128,1240.0,0.000000,53.5,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AFG,2006,,8.822967,112.080037,38.133311,1180.0,1.673640,52.9,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,AFG,2007,,10.190499,107.890921,40.672169,1140.0,5.020921,52.2,0.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,AFG,2008,,13.038878,103.678862,43.224932,1120.0,6.694561,51.4,2.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,AFG,2009,,14.345812,99.531599,45.738425,1090.0,9.205021,50.4,4.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,AFG,2010,,18.496521,95.404876,48.239469,1030.0,14.225941,49.5,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,AFG,2011,,22.577345,91.431093,50.647822,993.0,17.322176,48.4,8.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,AFG,2012,,25.595041,87.621370,52.956745,954.0,20.585774,47.2,10.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,AFG,2013,,28.932975,83.909065,55.206627,905.0,24.686192,46.0,13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,AFG,2014,,31.184121,80.339166,57.370202,858.0,28.619247,44.7,15.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,AFG,2015,,32.855428,76.830462,59.496690,810.0,32.635983,43.4,18.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,AFG,2016,,34.250375,73.580267,61.466505,786.0,34.644351,42.1,20.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,AFG,2017,,36.325848,70.444802,63.366787,701.0,41.757322,41.1,22.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,AFG,2018,,38.142928,67.572190,65.107764,673.0,44.100418,39.9,25.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,AFG,2019,,39.986104,64.940759,66.702570,638.0,47.029289,38.6,27.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,AFG,2020,,41.396926,62.541196,68.156851,638.0,47.029289,37.4,30.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,AFG,2021,,41.993067,60.269399,69.533698,638.0,47.029289,36.3,32.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
#Sheet3: HAI

indicatorCodeThird = ['HAI','U5M-Value','U5M-Index','MMR-Value','MMR-Index','STU-Value','STU-Index','GSSE-Value','GSSE-Index'
                     ,'ALR-Value','ALR-Index','GPIS-Value','GPIS-Index']
uniqueYearsThird = dfEvi['HAI']['Year'].unique()
dfEvi['HAI'] = dfEvi['HAI'].drop(columns = ['Ccode','Status','Country'])

for ele in uniqueYearsThird:
    dfEvi['HAI'][ele] = np.nan
dfEvi['HAI'].insert(2, 'IndicatorCode', '')
isoGrouped = dfEvi['HAI'].groupby('Iso', sort = False)

Final_dfThird = pd.DataFrame()
z = 0
for groupKey in isoGrouped.groups.keys():
    temp = isoGrouped.get_group(groupKey).apply(lambda x:x)
    temp = temp.reset_index(drop=True)
    for (code,i) in enumerate(indicatorCodeThird,0):
        values = isoGrouped.get_group(groupKey)[i].tolist()
        temp.loc[code,uniqueYearsThird] = values
        temp.loc[code,['IndicatorCode']] = i
    temp = temp.drop(columns = ['Year','HAI','U5M-Value','U5M-Index','MMR-Value','MMR-Index','STU-Value','STU-Index','GSSE-Value','GSSE-Index'
                     ,'ALR-Value','ALR-Index','GPIS-Value','GPIS-Index'])
    temp = temp.drop(range(13,temp.shape[0]))
    z = z + 1
    if z == 1:
        Final_dfThird = temp
    else:
        Final_dfThird = Final_dfThird.append(temp, ignore_index=True)
        
Final_dfThird.head(13)

,Iso,IndicatorCode,2002,2003,2004,2005,2006,2007,2008,2009,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,AFG,HAI,5.788194,6.033005,6.565748,7.098717,8.822967,10.190499,13.038878,14.345812,...,25.595041,28.932975,31.184121,32.855428,34.250375,36.325848,38.142928,39.986104,41.396926,41.993067
1,AFG,U5M-Value,128.691267,124.584845,120.430040,116.272989,112.080037,107.890921,103.678862,99.531599,...,87.621370,83.909065,80.339166,76.830462,73.580267,70.444802,67.572190,64.940759,62.541196,60.269399
2,AFG,U5M-Index,28.065899,30.554640,33.072703,35.592128,38.133311,40.672169,43.224932,45.738425,...,52.956745,55.206627,57.370202,59.496690,61.466505,63.366787,65.107764,66.702570,68.156851,69.533698
3,AFG,MMR-Value,1450.000000,1390.000000,1300.000000,1240.000000,1180.000000,1140.000000,1120.000000,1090.000000,...,954.000000,905.000000,858.000000,810.000000,786.000000,701.000000,673.000000,638.000000,638.000000,638.000000
4,AFG,MMR-Index,0.000000,0.000000,0.000000,0.000000,1.673640,5.020921,6.694561,9.205021,...,20.585774,24.686192,28.619247,32.635983,34.644351,41.757322,44.100418,47.029289,47.029289,47.029289

In [31]:
dfEvi['EVI'].head(5)

,Ccode,Iso,Country,Status,Year,EVI,AFF-Value,AFF-Index,REM-Value,REM-Index,...,XIN-Value,XIN-Index,LECZ-Value,LECZ-Index,DRY-Value,DRY-Index,AIN-Value,AIN-Index,VIC-Value,VIC-Index
0,4,AFG,Afghanistan,LDC,2002,50.110583,59.775038,99.618709,58.196678,60.245847,...,10.314511,20.629023,0.0,0.0,99.374879,99.374879,6.116083,24.951799,0.879832,68.022095
1,4,AFG,Afghanistan,LDC,2003,50.902468,57.065481,95.026240,57.954422,59.943027,...,11.094922,22.189845,0.0,0.0,99.385290,99.385290,6.660315,27.893594,0.926252,68.698538
2,4,AFG,Afghanistan,LDC,2004,50.819678,52.375205,87.076619,57.521351,59.401689,...,11.980660,23.961319,0.0,0.0,99.394834,99.394834,7.063447,30.072685,0.935230,68.825435
3,4,AFG,Afghanistan,LDC,2005,50.122079,47.632328,79.037844,57.027597,58.784496,...,15.062168,30.124336,0.0,0.0,99.403616,99.403616,6.950049,29.459726,0.922498,68.645101
4,4,AFG,Afghanistan,LDC,2006,48.788140,42.103057,69.666198,56.448170,58.060212,...,15.275943,30.551887,0.0,0.0,99.411723,99.411723,7.062763,30.068991,0.923607,68.660910

In [35]:
#Sheet4: EVI

indicatorCodeFourth = ['EVI','AFF-Value','AFF-Index','REM-Value','REM-Index', 'XCON-Value', 'XCON-Index',
                       'XIN-Value', 'XIN-Index', 'LECZ-Value', 'LECZ-Index', 'DRY-Value','DRY-Index',
                       'AIN-Value', 'AIN-Index', 'VIC-Value', 'VIC-Index']
uniqueYearsFourth = dfEvi['EVI']['Year'].unique()
dfEvi['EVI'] = dfEvi['EVI'].drop(columns = ['Ccode','Status','Country'])

for ele in uniqueYearsFourth:
    dfEvi['EVI'][ele] = np.nan
dfEvi['EVI'].insert(2, 'IndicatorCode', '')
isoGrouped = dfEvi['EVI'].groupby('Iso', sort = False)

Final_dfFourth = pd.DataFrame()
z = 0
for groupKey in isoGrouped.groups.keys():
    temp = isoGrouped.get_group(groupKey).apply(lambda x:x)
    temp = temp.reset_index(drop=True)
    for (code,i) in enumerate(indicatorCodeFourth,0):
        values = isoGrouped.get_group(groupKey)[i].tolist()
        temp.loc[code,uniqueYearsFourth] = values
        temp.loc[code,['IndicatorCode']] = i
    temp = temp.drop(columns = ['Year','EVI','AFF-Value','AFF-Index','REM-Value','REM-Index', 'XCON-Value', 'XCON-Index',
                       'XIN-Value', 'XIN-Index', 'LECZ-Value', 'LECZ-Index', 'DRY-Value','DRY-Index',
                       'AIN-Value', 'AIN-Index', 'VIC-Value', 'VIC-Index'])
    temp = temp.drop(range(17,temp.shape[0]))
    z = z + 1
    if z == 1:
        Final_dfFourth = temp
    else:
        Final_dfFourth = Final_dfFourth.append(temp, ignore_index=True)
        
Final_dfFourth.head(17)

,Iso,IndicatorCode,2002,2003,2004,2005,2006,2007,2008,2009,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,AFG,EVI,50.110583,50.902468,50.819678,50.122079,48.788140,47.643518,47.001208,46.105175,...,43.498666,42.890286,42.742670,42.722336,42.611061,42.831559,43.163960,43.339308,44.440394,44.838924
1,AFG,AFF-Value,59.775038,57.065481,52.375205,47.632328,42.103057,39.327812,37.210469,37.358753,...,34.087578,33.503474,31.910204,30.922630,30.074142,28.915596,28.085856,27.331756,26.134388,25.842050
2,AFG,AFF-Index,99.618709,95.026240,87.076619,79.037844,69.666198,64.962394,61.373675,61.625005,...,56.080641,55.090634,52.390175,50.716322,49.278207,47.314570,45.908231,44.630095,42.600657,42.105169
3,AFG,REM-Value,58.196678,57.954422,57.521351,57.027597,56.448170,55.804374,55.164999,54.485846,...,52.749147,52.227794,51.645248,51.198531,51.106009,51.373499,51.713759,51.809263,51.637471,51.506373
4,AFG,REM-Index,60.245847,59.943027,59.401689,58.784496,58.060212,57.255467,56.456249,55.607307,...,53.436434,52.784742,52.056561,51.498164,51.382511,51.716874,52.142199,52.261579,52.046838,51.882966
5,AFG,XCON-Value,0.338360,0.389707,0.421511,0.401933,0.388024,0.353072,0.334689,0.309844,...,0.268912,0.238243,0.270225,0.265088,0.276211,0.302342,0.322247,0.341208,0.354326,0.370250
6,AFG,XCON-Index,28.042312,34.083209,37.824845,35.521511,33.885195,29.773183,27.610436,24.687501,...,19.871971,16.263903,20.026415,19.422098,20.730656,23.804945,26.146686,28.377385,29.920689,31.794140
7,AFG,XIN-Value,10.314511,11.094922,11.980660,15.062168,15.275943,15.247715,13.329571,11.384384,...,7.752400,6.847933,6.219798,7.680987,7.288533,7.592873,8.151099,8.956574,10.282345,11.280218
8,AFG,XIN-Index,20.629023,22.189845,23.961319,30.124336,30.551887,30.495429,26.659143,22.768767,...,15.504801,13.695866,12.439595,15.361973,14.577066,15.185745,16.302198,17.913148,20.564690,22.560437
9,AFG,LECZ-Value,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,AFG,LECZ-Index,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11,AFG,DRY-Value,99.374879,99.385290,99.394834,99.403616,99.411723,99.419230,99.424599,99.429682,...,99.443425,99.447638,99.451601,99.369995,99.373516,98.956508,98.956912,98.957298,98.957667,98.958020
12,AFG,DRY-Index,99.374879,99.385290,99.394834,99.403616,99.411723,99.419230,99.424599,99.429682,...,99.443425,99.447638,99.451601,99.369995,99.373516,98.956508,98.956912,98.957298,98.957667,98.958020
13,AFG,AIN-Value,6.116083,6.660315,7.063447,6.950049,7.062763,7.136078,7.195724,7.229622,...,6.974907,6.996890,6.938292,6.902980,6.938398,6.937173,6.975920,6.744694,6.227707,6.227707
14,AFG,AIN-Index,24.951799,27.893594,30.072685,29.459726,30.068991,30.465284,30.787697,30.970929,...,29.594092,29.712921,29.396174,29.205296,29.396744,29.390124,29.599567,28.349699,25.555175,25.555175
15,AFG,VIC-Value,0.879832,0.926252,0.935230,0.922498,0.923607,0.931804,1.354436,1.360043,...,1.392021,1.629038,1.635770,1.638758,1.631914,1.648611,1.645128,1.641303,3.418298,3.412599
16,AFG,VIC-Index,68.022095,68.698538,68.825435,68.645101,68.660910,68.777155,73.697861,73.752207,...,74.057966,76.126581,76.180834,76.204844,76.149786,76.283707,76.255889,76.225261,85.877436,85.855485