In [190]:
import json
import pandas as pd
import numpy as np

#Add path of files
dfOHI = pd.read_csv('C:\\Users\\utkarsh.dixit\\Downloads\\Datasets\\ohi\\OHI_final_formatted.csv')
dfSeaAroundUs = pd.read_csv('C:\\Users\\utkarsh.dixit\\Downloads\\Datasets\\seaAroundUs\\seaAroundUs.csv')
dfEvi = pd.read_excel('C:\\Users\\utkarsh.dixit\\Downloads\\Datasets\\evi\\2021-retrospective-review-official.xlsx', sheet_name = ['Criteria','GNI','HAI','EVI'])
isoCountry = open('C:\\Users\\utkarsh.dixit\\PycharmProjects\\PovertyVulnerabilityAnalysis\\isonewcountryjs.json',)
countryDictionary = json.load(isoCountry)

def calPrevious(change, current):
    if (change < 0):
        return current + (-change)
    else:
        return current - change

In [188]:
dfOHI['IndicatorCode'] = dfOHI.goal.str.cat(df.dimension,sep="-")
dfOHI['CountryISO3'] = dfOHI['region_name'].map(countryDictionary)
dfOHI= dfOHI.drop(columns = ['goal', 'long_goal', 'dimension', 'region_id','region_name'])
dfOHI = dfOHI.reindex(columns =['scenario','CountryISO3','IndicatorCode','value'])
for ele in dfOHI.scenario.unique():
    dfOHI[ele] = np.nan
for ele in dfOHI.scenario.unique():
    dfOHI.loc[(dfOHI.scenario == ele), ele] = dfOHI.value
dfOHI= dfOHI.drop(columns = ['scenario', 'value'])
dfOHI.head(10)

,CountryISO3,IndicatorCode,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,GLA,AO-future,79.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CCK,AO-future,100.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CXR,AO-future,100.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NFK,AO-future,100.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AUS,AO-future,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NCL,AO-future,71.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,VUT,AO-future,49.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,SLB,AO-future,47.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,PLW,AO-future,66.18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,FSM,AO-future,49.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [191]:
dfSeaAroundUs['CountryISO3'] = dfSeaAroundUs['country'].map(countryDictionary)
dfSeaAroundUs['IndicatorCode'] = 'EPI-Score'
dfSeaAroundUs.rename(columns={"epi score": "2020","10-year change": "change" }, inplace = True)
dfSeaAroundUs['change'] = dfSeaAroundUs['change'].replace('-','0')
dfSeaAroundUs['2020'] = dfSeaAroundUs['2020'].replace('-','0')
dfSeaAroundUs['2010'] = dfSeaAroundUs.apply(lambda row : calPrevious(float(row["change"]),float(row['2020'])), axis = 1)
dfSeaAroundUs= dfSeaAroundUs.drop(columns = ['country', 'rank', 'change'])
dfSeaAroundUs = dfSeaAroundUs.reindex(columns =['CountryISO3','IndicatorCode','2020','2010'])
dfSeaAroundUs.head(5)

  CountryISO3 IndicatorCode  2020  2010
0         EST     EPI-Score  36.2  16.9
1         MHL     EPI-Score  35.4  12.3
2         VNM     EPI-Score  35.3  41.3
3         BGD     EPI-Score  34.5  46.4
4         SLE     EPI-Score  31.1  45.6